import random

listOfWords = ["APPLE", "BILBO", "CHORUSED", "DISIMAGINE",
"ENSURING", "FORMALISING", "GLITCHES", "HARMINE", "INDENTATION", "JACKED",
"KALPACS", "LAUNDRY", "MASKED", "NETTED", "OXFORD", "PARODY", "QUOTIENTS",
"RACERS", "SADNESS", "THYREOID", "UNDUE", "VENT", "WEDGED", "XERIC", "YOUTHHOOD",
"ZIFFS"]

print(random.choice(listOfWords))
input()
